[common]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 921600

[env:esp32dev]
extends = common
board = esp32dev
build_flags = -DLED_PIN=2 -DLED_IS_GPIO=1 -DBUTTON_PIN=0

[env:esp32dev-ota]
extends = env:esp32dev
upload_protocol = espota

[env:c3-supermini]
extends = common
board = lolin_c3_mini
build_flags = -DLED_PIN=8 -DLED_IS_GPIO=1 -DLED_ACTIVE_LOW=1 -DBUTTON_PIN=9

[env:c3-supermini-ota]
extends = env:c3-supermini
upload_protocol = espota
